### PR TITLE
Added systemd service

### PR DESCRIPTION
**Pull request by sruslanas**
Hi,

I have added systemd service for easier start/stop/status. Readme updated as an optional step.

### CODE REVIEW

**Comment by leoleovich** [comment]
Thanks, but I think there is too much of unnecessary stuff defined. For example pid or path to /opt (which is not that regular)
What about something like this? (we are using this in our infrastructure)
```
[Unit]
Description=ClusterHC light proxy that checks locally cluster
After=network.target

[Service]
User=clusterhc
ExecStart=/usr/local/bin/clusterhc
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by leoleovich** [comment]
Also user root is total overhead there.

**Comment by sruslanas** [comment]
Path to opt is specified in the readme.md, in my understanding consistency should be kept. About other lines, agree, it should be much more clean, thanks for the reference.

**Comment by leoleovich** [comment]
Ok, I will merge it with `/opt`, this is not that critical.Please squash it to 1 commit (you have commits which are canceling changes of previous).
You can use 
`rebase -i e0e2c13` and `fixup` all commit but the first one. And then force push to your fork.

It will be clean and nice :)
Thank you.

**Comment by sruslanas** [comment]
Thanks for tips. It took a while to me, but I glad, that I have learned that. I hope it looks ok now.

**Comment by leoleovich** [comment]
This looks ok ;)

**Pull request merged**
